lumada-common-services/gh-composite-actions

action.yaml

"I have updated the Slack notifications and summary part for the workflow dispatch event. There were some bugs in the previous pull request #87, including repetitive code and an incorrect commit message, which have now been resolved."
Updated Slack notification for Workflow dispatch event - https://hitachivantara-eng.slack.com/archives/C04PW2N50TY/p1690199072527239

[YKN-445] : Blackduck step not showing in GH job summary  and slack notification when trigger manually.

---

action.yaml

Fixed the incorrect Sonar link for the GitHub summary and the Slack notification for the manually dispatched event.

[YKN-450] : When manually dispatched, the sonar summary link is incorrect

---

README.md
action.yaml

Added Teams Notify action to send messages to a Microsoft Teams channel to help users keep track of all the defined steps in a workflow, along with additional workflow details.

[HCICD-462] : Notifications to Teams

---

README.md
action.yaml

Added Teams Notify action to send messages to a Microsoft Teams channel to help users keep track of all the defined steps in a workflow, along with additional workflow details.
Blackduck Fix adding additional parameter [detect.accuracy.required=NONE]

Notifications to Teams & Blackduck Fix

---

README.md

Added note about GITHUB_TOKEN parameter in Unit Test step. The unit test step requires the GitHub App installation access token (GITHUB_TOKEN) to be passed in order to function correctly.

[CLEANUP] - Added note about GITHUB_TOKEN parameter in Unit Test step.

---

action.yaml

Bug fixed - Hyperlink for the unit test is not generating for the pull request workflow
test link - https://github.com/lumada-common-services/multi-module-tester/actions/runs/6457119125

[HNC-444] -Hyperlink for the unit test is not generating for the pull request workflow

---

.github/workflows/update-release-notes.yml
docs/release.md

Note:- As Release Note Automation Process was stuck due to branch protection for the last release which was `1.6.0`. So `release.md` & confluence page where not updated with the latest release info which is `1.6.0` because of that I have manually added the latest release info in  `release.md` file so it will stay synchronized with the newest release done in future.

[HNC-467]: Fix Branch Protection Limitations for Release Automation

---

README.md
action.yaml

Include Citadel step tracking in GitHub summaries, Slack, and Teams. Additionally, based on team discussions, remove the Blackduck step from the merge workflow tracking.

[BUGFIX] HNC-474 : Add Citadel reports as a notification for Slack, Github Summary and Teams

---

.github/release-drafter-config.yml
.github/tag.sh
.github/workflows/release-drafter.yml
.github/workflows/update-release-notes.yml
docs/release.md

useful links:-
When a stable tag already exists then it updates the commit associated with the stable tag to the latest commit [link](https://github.com/lumada-common-services/lds-composite-action/actions/runs/6941822831/job/18883448250#step:6:152).
When a stable tag doesn't exist then creates new one with latest commit associated to stable tag [link](https://github.com/lumada-common-services/lds-composite-action/actions/runs/6942319979/job/18885028030#step:6:153)

[HNC-501] - Create stable tag for latest tagged release in gh-composite actions.

---

README.md
action.yaml

Added some extra validation, so it will not fail the UNIT_TEST step even if it does not find any reports; instead, it will set an error message. [Example](https://github.com/pentaho/pdi-plugins-ee/actions/runs/6903914500/job/18783562141#step:12:852)
For success, it will show a log like [this](https://github.com/pentaho/pdi-plugins-ee/actions/runs/6904637276/job/18785693346#step:12:1001). 
But if we want the build to fail when no report is found, there is already a parameter `fail-on-empty` provided by the `dorny/test-reporter@v1` action. If we set this value to `true`, it will fail the build after not finding reports. The default value for this parameter is set to `false`.
Also, the `dorny/test-reporter@v1` action now supports an output variable for the unit test report link. We can …

[HNC-502] - Unit test reporting is failing the build when no reports are found.

---

README.md
action.yaml

Added some extra validation, so it will not fail the UNIT_TEST step even if it does not find any reports; instead, it will set an error message.

[fix] HNC-502 - Unit test reporting is failing the build when no reports are found.

---

action.yaml

Update the composite action to display a 'boom 💥' symbol in the unit test step if the unit test command is successful but there are failed test cases

[fix] HNC-507 :  Summary should display a 'boom' symbol if there is a test failure

---

action.yaml

Update the conditions to display the correct summary link and symbol when we are passing `fail-on-error = true`.

[fix] HNC-507 : Summary should display a 'boom' symbol if there is a test failure

---

action.yaml

Added the `INTEGRATION_TEST` command type to the composite action for tracking in the reporting step. This integration step will only be tracked if it is run
Test cases:
- [first fail(fail-on-error: false) and second fail](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7031181499)
- [Unit fail(error: false) & Int fail(error:false)](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7031225104)
- [Unit fail(error: false) & Int pass(error:false)](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7031256117)
- [Unit fail(error: false) & Int pass(error:true)](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7031367147)
- [Unit fail(error: false) & Int …

[HNC-510] : Implement INTEGRATION_TEST command type in the composite action

---

action.yaml

Updated the composite action by adding deployment step tracking to reporting. Define the DEPLOY_DESC environment variable to include additional descriptions along with the "Deploy" keyword in the reporting.
Test Cases :
[with only cmd_type = DEPLOY](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7622461013#summary-20760549579)
[with cmd_type and DEPLOY_DESC env variable](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7622466696#summary-20760564733)

[HNC-546] : Add deployment step tracking to the composite action

---

README.md
action.yaml

Updated the composite action to track steps (BUILD, UNIT_TEST, INTEGRATION_TEST, TEST, DEPLOY) using comma-separated values. Now, we can track one or multiple `cmd_type` in a single step.
Added the new `cmd_type`  '**TEST**'  to the composite action for tracking any generic test step. Also added the new '**TEST_DESC**' environment variable to include additional descriptions along with the 'Test' keyword in the reporting. This generic test step will only be tracked if it is run.
Test Cases :
1. [(Build, Unit Test, IntegrationTest, Generic Test, Deploy)](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/7869001012)
2. [Separate Step (Build, Unit Test, IntegrationTest, Generic Test, Deploy)](https://github.com/lumada-common-services/honeycomb-samples/actions/runs/786921 …

[HNC-553] - Update the cmd_type tracking in the composite action.

---

README.md
action.yaml

Updated the composite action to track steps (BUILD, UNIT_TEST, INTEGRATION_TEST, TEST, DEPLOY) using comma-separated values. Now, we can track one or multiple cmd_type in a single step. For e.g., `cmd_type: BUILD,UNIT_TEST,DEPLOY`. Added the new cmd_type 'TEST' to the composite action for tracking any generic test step. Also added the new 'TEST_DESC' environment variable to include additional descriptions along with the 'Test' keyword in the reporting. This generic test step will only be tracked if it is run.

[feature] HNC-553 : Update the cmd_type tracking in the composite action.

---

action.yaml

Updated hv-actions/slack-action to use `stable` tag.

[fix] HNC-564 - Update hv-actions/slack-action to use stable tag

---

action.yaml
citadel/citadel.py

Update the Citadel scan script to fetch plugin names from the manifest file and determine the artifact zip URL for those plugins.
The script will only update the values if the Citadel config YAML file contains the specific placeholder mentioned below for each particular key. For more information, refer to [this.](https://hv-eng.atlassian.net/wiki/spaces/MCI/pages/30890459190/Honeycomb+and+Citadel+integration#Updating-values-in-the-config-file)

[feature] HNC-556 : Update the Citadel action script to include extra placeholders

---

action.yaml

Fixed the variable name value for the test reporter, as it was showing an incorrect variable name. It should show the variable name in the warning message as `unit_test_reporter`, not `unit_reporter`.

[BUGFIX] - Incorrect warning message showing in the test reporting.
